### PR TITLE
Better keyword triggering

### PR DESCRIPTION
**Pull request by Teccii**
Added a button that allows users to opt out of the trigger, since it's a little annoying. I made a new model for the trigger cuz I got a bit confused by pre-existing ones. Maybe in the future when there are more triggers this can be modified to work for multiple triggers, since right now this would opt you out of every trigger if there were multiple ones.

image

### CODE REVIEW

**Comment by 3vilN355** [comment]
Check https://github.com/DaniDiscord/Dani-Server-Utils/pull/38 for relevant feedback

**Comment by Teccii** [comment]
I think I covered everything you gave feedback on.

**Comment by 3vilN355** [comment]
Forgot to mention, we should probably have a better way of introducing these to the database than manually adding them (because that's annoying to do lol), maybe just add somewhere in initialization that it adds a pre-defined list?

**Comment by Teccii** [comment]
I tried for a bit and couldn't really find an agreeable way to add that. I could make it generate Settings _with_ a predefined list of triggers (only works for guilds without existing settings so unless you wanna nuke the server settings then no), and I could also make it forcibly add the predefined list of triggers to every guild, but that approach doesn't sit right with me.

Also, the commands aren't that annoying to work with? At least I don't think so. /trigger add has more options than the others, but that's necessary so that you can add triggers more easily with the command.
image
image

**Pull request merged**
